// Initialize jsPDF
const { jsPDF } = window.jspdf;

// Carousel functionality
const carouselImgs = document.querySelectorAll('.carousel-img');
const carouselDots = document.querySelectorAll('.carousel-dot');
let currentIndex = 0;
let interval;

function showSlide(index) {
    carouselImgs.forEach(img => img.classList.remove('active'));
    carouselDots.forEach(dot => dot.classList.remove('active'));
    
    carouselImgs[index].classList.add('active');
    carouselDots[index].classList.add('active');
    currentIndex = index;
}

function nextSlide() {
    const nextIndex = (currentIndex + 1) % carouselImgs.length;
    showSlide(nextIndex);
}

function startCarousel() {
    interval = setInterval(nextSlide, 5000);
}

carouselDots.forEach((dot, index) => {
    dot.addEventListener('click', () => {
    clearInterval(interval);
    showSlide(index);
    startCarousel();
    });
});

startCarousel();

// Profile dropdown functionality
const profileDropdown = document.getElementById('profileDropdown');
const profileBtn = document.getElementById('profileBtn');

profileBtn.addEventListener('click', (e) => {
    e.stopPropagation();
    profileDropdown.classList.toggle('open');
});

document.addEventListener('click', () => {
    profileDropdown.classList.remove('open');
});

// Download About Us as PDF functionality
document.getElementById('downloadAboutBtn').addEventListener('click', function() {
    // Create a new PDF document
    const doc = new jsPDF();
    
    // Add logo (if available)
    // doc.addImage('images/sic logo.jpg', 'JPEG', 10, 10, 30, 30);
    
    // Set document properties
    doc.setProperties({
    title: 'SICLife - About Us',
    subject: 'Company Information',
    author: 'SICLife',
    keywords: 'siclife, about, mission, vision',
    creator: 'SICLife Intern Tracker'
    });
    
    // Add title
    doc.setFontSize(20);
    doc.setTextColor(0, 119, 181); // SICLife blue
    doc.text('SICLife - About Us', 105, 20, { align: 'center' });
    
    // Reset font for content
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0); // Black
    
    // Add mission section
    doc.setFont(undefined, 'bold');
    doc.text('Our Mission:', 15, 40);
    doc.setFont(undefined, 'normal');
    doc.text('To provide innovative insurance solutions that secure the future of our', 15, 50);
    doc.text('customers through excellent service and financial strength.', 15, 55);
    
    // Add vision section
    doc.setFont(undefined, 'bold');
    doc.text('Our Vision:', 15, 70);
    doc.setFont(undefined, 'normal');
    doc.text('To be the leading life insurance company in Ghana and beyond,', 15, 80);
    doc.text('recognized for our customer-centric approach and sustainable growth.', 15, 85);
    
    // Add objectives section
    doc.setFont(undefined, 'bold');
    doc.text('Our Objectives:', 15, 100);
    doc.setFont(undefined, 'normal');
    
    const objectives = [
    '• Provide financial security to individuals and businesses',
    '• Deliver exceptional customer service',
    '• Maintain strong corporate governance',
    '• Invest in our employees\' development',
    '• Contribute positively to our communities'
    ];
    
    objectives.forEach((obj, i) => {
    doc.text(obj, 20, 110 + (i * 7));
    });
    
    // Add footer
    doc.setFontSize(10);
    doc.setTextColor(100, 100, 100);
    doc.text('Generated by SICLife Intern Tracker', 105, 290, { align: 'center' });
    
    // Save the PDF
    doc.save('SICLife_About_Us.pdf');
});

// Photo Gallery functionality
const galleryBtn = document.getElementById('galleryBtn');
const galleryModal = document.getElementById('galleryModal');
const closeBtn = document.querySelector('.close-btn');
const galleryItems = document.querySelectorAll('.gallery-item');
const prevBtn = document.querySelector('.gallery-prev');
const nextBtn = document.querySelector('.gallery-next');
let currentGalleryIndex = 0;

galleryBtn.addEventListener('click', function() {
    galleryModal.style.display = 'flex';
    showGalleryItem(currentGalleryIndex);
});

closeBtn.addEventListener('click', function() {
    galleryModal.style.display = 'none';
});

window.addEventListener('click', function(event) {
    if (event.target === galleryModal) {
    galleryModal.style.display = 'none';
    }
});

function showGalleryItem(index) {
    galleryItems.forEach(item => item.classList.remove('active'));
    galleryItems[index].classList.add('active');
}

prevBtn.addEventListener('click', function() {
    currentGalleryIndex = (currentGalleryIndex - 1 + galleryItems.length) % galleryItems.length;
    showGalleryItem(currentGalleryIndex);
});

nextBtn.addEventListener('click', function() {
    currentGalleryIndex = (currentGalleryIndex + 1) % galleryItems.length;
    showGalleryItem(currentGalleryIndex);
});